<a href="https://colab.research.google.com/github/soumikdhua/SAiDL-Summer-Assignment-2019/blob/master/Numpy%20Neural%20Network/XOR-XNOR%20Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#XOR-XNOR Gate
---
I have created neural net in numpy which either computes the XOR
or the XNOR of two two bit binary numbers depending on the value of a third input. If the third
input is 0, the neural net computes the XOR of the two numbers and if the third input is
1, the neural net computes the XNOR of the two numbers.

In [0]:
'''Importing numpy'''
import numpy as np

In [0]:
'''Implementing the sigmoid and sigmoid derivative function'''

def sigmoid(x):
  return 1/(1+np.exp(-x))
  
def sigmoid_deriv(x):  
  return (x*(1-x))



    

In [0]:
'''Input data for XOR-XNOR Gate
   I have divided the two input numbers into subparts. So columns 1 & 2 represent the first & second bits of the first number.
   Similarly, columns 3 & 4 represent first & second bits of the second number.
   Last column in the input decides whether we calculate the XOR or XNOR of the two two bit numbers.
   If the input is 0, the neural net computes the XOR of the two numbers and if the input is 1, the neural net computes the XNOR of the two numbers.'''

X = np.array([[0,0,0,0,0],

            [0,0,0,1,0],

            [0,0,1,0,0],

            [0,0,1,1,0],

            [0,1,0,0,0],

            [0,1,0,1,0],

            [0,1,1,0,0],

            [0,1,1,1,0],

            [1,0,0,0,0],

            [1,0,0,1,0],

            [1,0,1,0,0],

            [1,0,1,1,0],

            [1,1,0,0,0],

            [1,1,0,1,0],

            [1,1,1,0,0],

            [1,1,1,1,0],
             
             
            [0,0,0,0,1],

            [0,0,0,1,1],

            [0,0,1,0,1],

            [0,0,1,1,1],

            [0,1,0,0,1],

            [0,1,0,1,1],

            [0,1,1,0,1],

            [0,1,1,1,1],

            [1,0,0,0,1],

            [1,0,0,1,1],

            [1,0,1,0,1],

            [1,0,1,1,1],

            [1,1,0,0,1],

            [1,1,0,1,1],

            [1,1,1,0,1],

            [1,1,1,1,1]
             
            ])





'''Output data for XOR-XNOR Gate'''

y = np.array([[0,0],

             [0,1],

             [1,0],

             [1,1],

             [0,1],

             [0,0],

             [1,1],

             [1,0],

             [1,0],

             [1,1],

             [0,0],

             [0,1],

             [1,1],

             [1,0],

             [0,1],

             [0,0],
              
              
              
             [1,1],

             [1,0],

             [0,1],

             [0,0],

             [1,0],

             [1,1],

             [0,0],

             [0,1],

             [0,1],

             [0,0],

             [1,1],

             [1,0],

             [0,0],

             [0,1],

             [1,0],

             [1,1]
             
             ])




In [0]:
'''The seed is set to return the same random numbers each time'''

np.random.seed(1)                                     

In [0]:
'''An array of bias terms'''
bias=np.ones((X.shape[0],1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [0]:
'''Appending the bias term to the inputs'''
X_train = np.append(X, bias, axis = 1)
X_train

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 1.],
       [0., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 1., 0., 1.],
       [1., 1., 0., 0., 0., 1.],
       [1., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0., 1.],
       [1., 1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 1., 1., 1.],
       [0., 1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1., 1.],
       [1., 0., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1., 1.],
       [1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 1., 1., 1.],
       [1.

In [0]:
'''Initializing the weights'''

w0 = 2*np.random.random((6,16)) - 1  # 6x16 matrix of weights ((4 inputs + 1 bias) x 16 nodes in the hidden layer)

w1 = 2*np.random.random((16,2)) - 1  # 16x2 matrix of weights. (16 nodes x 2 outputs) - no bias term in the hidden layer.



In [0]:
'''Training our model'''

epochs=100000

for epoch in range(epochs):



    # Forward propagation

    lay0 = X_train

    lay1 = sigmoid(np.dot(lay0, w0))

    lay2 = sigmoid(np.dot(lay1, w1))



    # Back propagation

    lay2_error = y - lay2

    if((epoch+1) % 5000) == 0:                                                  # Print the error every 5000 steps.

        print(("Error after epoch {} - ").format(epoch+1) + str(np.mean(np.abs(lay2_error))))



    lay2_delta = lay2_error*sigmoid_deriv(lay2)



    lay1_error = lay2_delta.dot(w1.T)



    lay1_delta = lay1_error * sigmoid_deriv(lay1)



    #update weights

    w1 += lay1.T.dot(lay2_delta)

    w0 += lay0.T.dot(lay1_delta)



print("\nThe output after training is -")

print(lay2)

Error after epoch 5000 - 0.00500907750847357
Error after epoch 10000 - 0.003422878825331286
Error after epoch 15000 - 0.0027496346741464027
Error after epoch 20000 - 0.0023567436847620688
Error after epoch 25000 - 0.0020922832739218473
Error after epoch 30000 - 0.0018990074414989408
Error after epoch 35000 - 0.0017499548427937013
Error after epoch 40000 - 0.0016305611773266757
Error after epoch 45000 - 0.0015321852938779109
Error after epoch 50000 - 0.0014493366782500237
Error after epoch 55000 - 0.0013783390800580862
Error after epoch 60000 - 0.0013166269494314094
Error after epoch 65000 - 0.0012623487106758332
Error after epoch 70000 - 0.0012141303931538807
Error after epoch 75000 - 0.0011709282894373893
Error after epoch 80000 - 0.0011319335679001192
Error after epoch 85000 - 0.001096508502834942
Error after epoch 90000 - 0.001064142646187741
Error after epoch 95000 - 0.0010344219711154626
Error after epoch 100000 - 0.0010070066840181923

The output after training is -
[[7.40629567e

In [0]:
'''Print outputs after training rounded off to nearest integer'''

print(np.around(lay2))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [0]:
'''Our custom testcases. You can modify the testcases as per your choice.
   Columns 1 & 2 represent the first & second bits of the first number.
   Similarly, columns 3 & 4 represent the first & second bits of the second number.
   Last column in the input decides whether we calculate the XOR or XNOR of the two two bit numbers.
   If the input is 0, the neural net computes the XOR of the two numbers and if the input is 1, the neural net computes the XNOR of the two numbers.'''
   
x=np.array([[0,0,0,0,1],

            [0,0,0,1,1],

            [0,0,1,0,1],

            [0,0,1,1,1],

            [0,1,0,0,1]])


In [0]:
'''Adding the bias term to the inputs'''
bias=np.ones((x.shape[0],1))
X_test = np.append(x, bias, axis = 1)

In [0]:
'''Find the predicted outputs and printing them'''
lay0 = X_test

lay1 = sigmoid(np.dot(lay0, w0))

lay2 = sigmoid(np.dot(lay1, w1))

print(np.around(lay2))

[[1. 1.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 0.]]
